apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minikube
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: quarky-test
          servicePort: 8080
